### PR TITLE
memory leak

### PR DESCRIPTION
**Pull request by wangii**
AudioQueueBuffer not freed.

### CODE REVIEW

**Comment by Bo98** [comment]
Does `AudioQueueDispose` not cover this?

**Comment by Bo98** [comment]
From `AudioQueueDispose` [docs](https://developer.apple.com/library/ios/documentation/MusicAudio/Reference/AudioQueueReference/index.html#//apple_ref/doc/uid/TP40005117-CH3-SW16):
> Disposing of an audio queue also disposes of its buffers. Call this function only if you want to dispose of a particular buffer while continuing to use an audio queue.

**Comment by wangii** [comment]
yes, according to the doc, it should be released. but after manually add AudioQueueFreeBuffer, it leaked less memory: from around 1.6M to few hundred K.

**Comment by Bo98** [comment]
Interesting, I don't get any leaks on my end. I'll merge it anyway since it can't hurt.

You might have to move the `AudioQueueStop` call to before the freeing of buffers though, assuming the docs are not wrong at that too.

> You can dispose of a buffer only when the audio queue that owns it is stopped

**Comment by wangii** [comment]
Found the problem. it's a silly mistake on my side. Sorry for trouble!

**Comment by Bo98** [comment]
No problem!

**Pull request closed without merging**
